import sys
from io import StringIO
from langchain.schema import SystemMessage, HumanMessage

class AutonomousAgent:
    """
    Agentic Workflow: Executes Python code generated by LLM 
    with a built-in self-correction feedback loop.
    """
    
    def __init__(self, model_provider):
        self.llm = model_provider
        print("🔥 Execution Engine Ready!")

    def _run_code_logic(self, code_string):
        """Executes code and captures stdout or exceptions."""
        old_stdout = sys.stdout
        redirected_output = sys.stdout = StringIO()
        try:
            # Code Execution Context
            exec(code_string)
            sys.stdout = old_stdout
            return {"status": "success", "output": redirected_output.getvalue()}
        except Exception as e:
            sys.stdout = old_stdout
            return {"status": "error", "output": str(e)}

    def autonomous_experiment_runner(self, task, retries=3):
        """The main loop for Hypothesis -> Code -> Execution -> Refinement"""
        print(f"\n🔬 Mission Started: {task}")
        feedback = ""

        for i in range(retries):
            prompt = f"""
            Task: {task}
            Previous Error (if any): {feedback}

            Instructions:
            1. Write robust Python code using synthetic data.
            2. Use scientific libraries (numpy, matplotlib, pandas) if needed.
            3. Print the final result clearly.
            4. Respond ONLY with the raw code block (no markdown text).
            """

            # LLM Call (Assuming 'llm' is passed/initialized)
            response = self.llm.invoke([
                SystemMessage(content="You are an Autonomous Research Engineer."),
                HumanMessage(content=prompt)
            ]).content

            # Code Cleaning Logic
            clean_code = response.replace("```python", "").replace("```", "").strip()

            print(f"🚀 Attempt {i+1}: Running AI-Generated Logic...")
            result = self._run_code_logic(clean_code)

            if result["status"] == "success":
                print("✅ Success! Experiment results captured.")
                return result["output"]
            else:
                print(f"❌ Execution Failed: {result['output']}")
                feedback = result["output"] # Feedback loop for next retry

        return "Maximum retries reached. Agent unable to self-correct."

# --- Usage Example ---
# agent = AutonomousAgent(llm)
# task = "Create a dataset of 5 potential medicine compounds with random efficacy scores and plot a bar chart."
# print(agent.autonomous_experiment_runner(task))
